### ISSUE TITLE
Fetch returning empty list

### ISSUE THREAD

**Issue by pranita-s** [ropensci/rdataretriever#131]
The fetch function returns an empty list for a given dataset, eg - "airports" as shown in following image - 

![rdataretriever](https://user-images.githubusercontent.com/14193989/36761178-e52cf162-1c43-11e8-9131-886362b6d992.png)
Reason - temp_path variable records the temporary path. Line number 121 records the file path and tries to install the files but "file.path(temp_path, '{db}_{table}.csv')" does not record absolute path, therefore retriever tries to search temporary folder in the current directory and fails to find it. Retriever does not display "Directory does not exist error".

**Comment by ethanwhite** [comment]
Thanks for reporting this @pranita-s and for doing a great job tracking down the issue!

This is a pretty confusing one because it looks like it should work and we have a test passing for `fetch` on continuous integration. I looked around a bit myself and what I'm seeing suggests that there may be a change in capitalization that is messing with the proper use of `tempdir()`:

```
> tempdir()
[1] "/tmp/Rtmp6kF5lc"
> list.files("/tmp/Rtmp6kF5lc")
[1] "stuffystuff.csv"
> rdataretriever::install('airports', 'csv', data_dir = '/temp/Rtmp6KF5lc')
=> Installing airports
[Errno 2] No such file or directory: '/temp/rtmp6kf5lc/airports_airports.csv'
Done!
```

So, in my case `tempdir()` exists, it is a full path, I put something in it, but when I run `install` it errors because the capitalization of the directory has changed to be all lower case.

A little more looking suggests that this is happening in the main Python package:

```
$ mkdir TESTER
$ retriever install csv mammal-masses --table_name TESTER/test.csv
=> Installing mammal-masses
[Errno 2] No such file or directory: 'tester/test.csv'
Done!
```

So I'm guessing we're lower casing the data directory incorrectly in the core retriever somewhere which is causing this issue.

**Comment by ethanwhite** [comment]
This is now fixed in the core retriever https://github.com/weecology/retriever/issues/1101, but since it is broken in the last release I think we should handle this here as a special case as mentioned in #132.

**Comment by ethanwhite** [comment]
Fixed by @pranita-s in 1a46e6c.

**Comment by pranita-s** [comment]
@ethanwhite @henrykironde The updated fetch command has been merged with master branch but, after updating the scripts, the fetch command through "rdataretriever" package is still not working. 
Is there a different process for updating the package in R with updated scripts?

**Comment by henrykironde** [comment]
Since you are working based on both changes in the core Python package and R package, you will have to checkout the retriever repository and install retriever from that repo. (`pip install . --upgrade`)
Then, with the new R package update installed too, I believe everything will be fine.

After installing the retriever python library, I recommend you do a `retriever reset all`, Then using R, you can update the scripts.

**Comment by ethanwhite** [comment]
@pranita-s - it looks like thinks are working for me, including with the last release of the retriever (i.e., without needing to update the Python package).

Did you update your local installation of the R package?
